### ISSUE TITLE
FreePBX 17 compatibility

### ISSUE THREAD

**Issue by PlanetSmasher** [Massi-X/freepbx-carddavmiddleware-ui#16]
**Component**
Please flag the component that this issue relates to:

- [ ] UI
- [x] Core

**Describe the bug**
On a fresh FreePBX 17 Installation I tried to add the module, but it failed.

**To Reproduce**
1. Go Module Admin and import module
2. install imported module
3. activate the module
4. see error 
  ` Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
Declaration of Psr\Log\AbstractLogger::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void`

**Expected behavior**
Adding the module should not lead to error messages.
Adding compatibility to FreePBX17 on Debian

**Screenshots**

**System**
 - PBX Version and distribution: FreePBX 17
 - Base OS System Debian Bookworm

**Comment by Massi-X** [comment]
Hi and thank you for using the module! First thing first, are you using the latest version I imagine (2.1.2)?
This is a problem with one library I'm using, I will shortly attach here a test version with updated dependencies to see if that fixes the problem

**Comment by PlanetSmasher** [comment]
Thanks for the great Module!!! it works like a charm on my production system.
I use the latest 2.1.2 for this test that is correct :)


I just wanted to adress this issue so that others will know that there were little problems at the moment.

**Comment by TheGreyDiamond** [comment]
Hey, there just wanted to chime in to say I've gotten the same issue. Also running the newest version on FreePBX 17.0.19.7 with Debian Bookworm. Looking forward to a fix!

**Comment by Massi-X** [comment]
Great! I found the issue and am looking for a way to fix it cause I still want to support both 16 and 17 with a single release of the module!

**Comment by polcape** [comment]
I have same issue on 17 version

**Comment by Massi-X** [comment]
Hi @polcape the new version is almost ready, continue to watch this issue for updates

**Comment by Massi-X** [comment]
Fixed in [2.2.0](https://carddavmiddleware.massi-x.dev/index.php?download=carddavmiddleware_2.2.0.tar.gz)
