### ISSUE TITLE
Tips for FreePBX17

### ISSUE THREAD

**Issue by polcape** [Massi-X/freepbx-carddavmiddleware-ui#17]
This is a tips not an issue related to this module.

I test the component on FreePBX 17 and when I use the Regular Expression 2 module of Superfecta I get an error "Automatic conversion of false to array is deprecated".

I solved to change the line 47 of source-Regular_Expressions_2.module of Superfecta
			$post = false;
to
			$post = [];

**Comment by Massi-X** [comment]
Hi this issue is related to superfecta then (even though that module was my implementation). We should make a PR to that repository then.

May I ask why would you send an empty POST request? How can this happen?

**Comment by polcape** [comment]
I only try in debug mode the scheme in superfecta module with a number I had in CARDDAV addressbook to test.

I think they switch to PHP 8.2 in FreePBX and in that version the "Automatic conversion of false to array" (valid in previous version) is not valid anymore.

**Comment by Massi-X** [comment]
I think the issue resides in the debug mode then, because it probably doesn't set the POST parameter correctly (if not at all). Granted, your fix is correct and should be implemented anyway. I will have a look and eventually raise a PR to superfecta.

I'm closing this as it is not related to carddavmiddleware, thank you for now.

**Comment by polcape** [comment]
Hi @Massi-X ,

thanks!

I found another issue that broke your module if I choose FULL "Superfecta Compatibility" becasue if I don't have a numebr in my address book the module reply with no data and iin Superfecta I get another exception.

Tha problem is always the compatibility with PHP 8.x, (the trim() function in line 17 don't work anymore on null value) and I solved changhing the line 40 of source-Regular_Expressions_2.module from
		$caller_id = null;
to
		$caller_id = "";

**Comment by Massi-X** [comment]
You're a bug hunter! I will raise another PR for this shorty so it gets fixed!
