### ISSUE TITLE
Output separators

### ISSUE THREAD

**Issue by polcape** [Massi-X/freepbx-carddavmiddleware-ui#18]
It would be nice add the possibility to choose the order of CNAM/Phonebook Output and add the field Lastname (now missed) to format name in different order from the default one.

For example: _Company: Name Lastname_ or _Lastname Name_

Thanks

**Comment by Massi-X** [comment]
Hi a few thoughts about this:
- Reordering is already possible by dragging the 'chips' inside the UI
- I will surely implement the last name in a future release, thanks for the suggestion 
- Inserting commas, colons and other separators is currently not possible, I will look into it

**Comment by polcape** [comment]
Oh, @Massi-X thanks for suggestion and for the future improvements.

**Comment by Massi-X** [comment]
Implementation complete in [2.3.0](https://carddavmiddleware.massi-x.dev/#2.3.0)
